create_automation:
  name: Create automation
  description: Create a Home Assistant automation using natural language description powered by Claude AI
  fields:
    description:
      name: Description
      description: Natural language description of the automation to create
      required: true
      example: "Turn on the living room lights when I arrive home"
      selector:
        text:
          multiline: true
    validate_only:
      name: Validate only
      description: Only validate the automation without creating it
      default: false
      selector:
        boolean:
    preview:
      name: Preview
      description: Preview the generated YAML without creating the automation
      default: false
      selector:
        boolean:

validate_automation:
  name: Validate automation
  description: Validate automation YAML syntax
  fields:
    yaml_content:
      name: YAML content
      description: YAML content to validate
      required: true
      example: "- alias: Test\n  trigger: []"
      selector:
        text:
          multiline: true
